"use strict";
exports.__esModule = true;
exports.ROAD_TILE_1 = { tileX: 0, tileY: 0 };
exports.ROAD_TILE_2 = { tileX: 1, tileY: 0 };
exports.ROAD_TILE_3 = { tileX: 2, tileY: 0 };
exports.ROAD_TILE_4 = { tileX: 0, tileY: 1 };
exports.ROAD_TILE_5 = { tileX: 1, tileY: 1 };
exports.ROAD_TILE_6 = { tileX: 2, tileY: 1 };
exports.ROAD_TILE_7 = { tileX: 0, tileY: 2 };
exports.ROAD_TILE_8 = { tileX: 1, tileY: 2 };
exports.ROAD_TILE_9 = { tileX: 2, tileY: 2 };
